name: Web Automation

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches: [master]
  release:
    types: [created] 

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
      
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Test with Maven
        run: |
          mvn clean install test
          mkdir Execution_Results && cp target/surefire-reports/ Execution_Results
          
      - name: Execution Results
        uses: actions/upload-artifact@v3
        with: 
              name: Latest Results
              path: Execution_Results
